import logging
from odoo import models, fields, _
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class AccountMove(models.Model):
    _inherit = "account.move"

    def action_post(self):
        """
        Extend action_post to trigger auto-payment if the invoice
        comes from a Recurring Contract with a Token.
        """
        # 1. Standard Post Logic
        res = super().action_post()

        # 2. Check for Auto-Pay candidates
        for invoice in self:
            # Only process if:
            # - It's a Customer Invoice ('out_invoice')
            # - It's unpaid
            # - It was generated by the Recurring Invoicer
            if (invoice.move_type == 'out_invoice' and
                    invoice.payment_state == 'not_paid' and
                    getattr(invoice, 'recurring_invoicer_id', False)):  # Safe access

                # Find the related contract group via invoice lines
                contract_lines = invoice.invoice_line_ids.mapped('contract_id')
                if contract_lines:
                    # All lines in one invoice belong to the same group
                    group = contract_lines[0].group_id

                    # 3. Trigger Charge if Token exists
                    if group.payment_token_id and group.payment_token_id.active:
                        _logger.info(f"Auto-charging Invoice {invoice.name} with Token {group.payment_token_id.id}")
                        invoice._charge_postfinance_token(group.payment_token_id)

        return res

    def _charge_postfinance_token(self, token):
        """
        Executes the S2S (Server to Server) transaction.
        """
        self.ensure_one()
        acquirer = token.acquirer_id

        # 1. Create Transaction (Draft)
        tx_vals = {
            'acquirer_id': acquirer.id,
            'amount': self.amount_total,
            'currency_id': self.currency_id.id,
            'partner_id': self.partner_id.id,
            'reference': self.payment_reference or self.name,
            'payment_token_id': token.id,
            'type': 'server2server',
            'state': 'draft',
            'invoice_ids': [(6, 0, self.ids)],
            'callback_model_id': self.env['ir.model']._get_id('account.move'),
            'callback_res_id': self.id,
        }

        tx = self.env['payment.transaction'].create(tx_vals)

        # 2. Execute PostFinance Charge
        if acquirer.provider == 'postfinance':
            res = acquirer.postfinance_charge_token(
                token,
                self.amount_total,
                self.currency_id,
                tx.reference,
                self.partner_id
            )

            if res.get('success'):
                # Update Transaction State
                tx._set_transaction_done()
                tx.write({
                    'acquirer_reference': res.get('transaction_id'),
                    'is_processed': True  # Mark as processed to prevent double handling
                })

                # 3. Reconcile!
                # This Odoo standard method looks at 'invoice_ids', creates the payment,
                # and reconciles it with the invoice.
                tx._post_process_after_done()

            else:
                # Handle Failure
                error_msg = res.get('error', 'Unknown Error')
                tx._set_transaction_error(msg=error_msg)
                self.message_post(body=f"Auto-payment failed via PostFinance: {error_msg}")